apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-cert
  namespace: cert-manager
spec:
  secretName: wildcard-tls
  dnsNames:
  - "*.vinitham.online"
  - vinitham.online
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
